import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import RealtimeBackground from "@/components/shared/market";
import { AppBar } from "@mui/material";
import NavBar from "@/components/shared/navigation/nav-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{display: 'flex', flexDirection: "column"}}
      >
        <RealtimeBackground />
        <Providers>
          <AppBar
            position="fixed"
            elevation={0}
            sx={{
              background: "rgba(0,0,0,0.35)",
              backdropFilter: "blur(3px)",
              borderBottom: "1px solid rgba(255,255,255,0.1)",
            }}
          >
            <NavBar />
          </AppBar>
          {children}
        </Providers>
      </body>
    </html>
  );
}
