import { Box } from "@mui/material";
import { useEffect, useState } from "react";
import LemoCircle from "./lemo-circle";
const words = [
  "var",
  "let",
  "const",
  "function",
  "return",
  "if",
  "else",
  "switch",
  "case",
  "break",
  "continue",
  "for",
  "while",
  "do",
  "try",
  "catch",
  "finally",
  "throw",
  "class",
  "extends",
  "super",
  "import",
  "export",
  "default",
  "new",
  "this",
  "typeof",
  "instanceof",
  "delete",
  "in",
  "of",
  "with",
  "yield",
  "await",
  "async",
  "Promise",
  "map",
  "filter",
  "reduce",
  "find",
  "forEach",
  "push",
  "pop",
  "shift",
  "unshift",
  "splice",
  "slice",
  "concat",
  "join",
  "split",
  "includes",
  "indexOf",
  "Object",
  "Array",
  "String",
  "Number",
  "Boolean",
  "Math",
  "Date",
  "JSON",
  "parse",
  "stringify",
  "setTimeout",
  "setInterval",
  "clearTimeout",
  "clearInterval",
  "document",
  "window",
  "console",
  "log",
  "error",
  "warn",
  "fetch",
  "XMLHttpRequest",
  "localStorage",
  "sessionStorage",
  "navigator",
  "location",
  "history",
  "addEventListener",
  "removeEventListener",
  "querySelector",
  "querySelectorAll",
  "getElementById",
  "getElementsByClassName",
  "innerHTML",
  "innerText",
  "textContent",
  "style",
  "classList",
  "appendChild",
  "removeChild",
  "createElement",
  "cloneNode",

  "interface",
  "type",
  "enum",
  "namespace",
  "module",
  "public",
  "private",
  "protected",
  "readonly",
  "abstract",
  "implements",
  "declare",
  "unknown",
  "never",
  "any",
  "void",
  "tuple",
  "keyof",
  "typeof",
  "as",
  "asserts",
  "satisfies",

  "html",
  "head",
  "body",
  "title",
  "meta",
  "link",
  "script",
  "style",
  "div",
  "span",
  "p",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "a",
  "img",
  "ul",
  "ol",
  "li",
  "table",
  "tr",
  "td",
  "th",
  "thead",
  "tbody",
  "form",
  "input",
  "textarea",
  "button",
  "select",
  "option",
  "label",
  "fieldset",
  "legend",
  "iframe",
  "canvas",
  "svg",
  "video",
  "audio",
  "source",
  "track",
  "section",
  "article",
  "aside",
  "nav",
  "header",
  "footer",
  "main",
  "figure",
  "figcaption",
  "br",
  "hr",

  "color",
  "background",
  "margin",
  "padding",
  "border",
  "width",
  "height",
  "max-width",
  "min-width",
  "max-height",
  "min-height",
  "display",
  "flex",
  "grid",
  "position",
  "absolute",
  "relative",
  "fixed",
  "sticky",
  "top",
  "bottom",
  "left",
  "right",
  "z-index",
  "overflow",
  "clip-path",
  "transform",
  "translate",
  "rotate",
  "scale",
  "skew",
  "transition",
  "animation",
  "keyframes",
  "opacity",
  "visibility",
  "cursor",
  "font-size",
  "font-family",
  "font-weight",
  "line-height",
  "letter-spacing",
  "text-align",
  "text-decoration",
  "text-transform",
  "white-space",
  "word-break",
  "box-shadow",
  "text-shadow",
  "border-radius",
  "background-image",
  "background-size",
  "background-position",
  "background-repeat",
  "gradient",
  "flex-direction",
  "justify-content",
  "align-items",
  "align-content",
  "gap",
  "grid-template-columns",
  "grid-template-rows",
  "grid-area",
  "grid-gap",
  "media",
  "hover",
  "focus",
  "active",
  "nth-child",
  "first-child",
  "last-child",
  "before",
  "after",

  "API",
  "REST",
  "GraphQL",
  "CRUD",
  "GET",
  "POST",
  "PUT",
  "DELETE",
  "PATCH",
  "HTTP",
  "HTTPS",
  "TCP",
  "UDP",
  "WebSocket",
  "SocketIO",
  "JWT",
  "OAuth",
  "session",
  "cookie",
  "middleware",
  "router",
  "controller",
  "model",
  "view",
  "MVC",
  "SSR",
  "CSR",
  "hydration",
  "state",
  "props",
  "context",
  "hook",
  "useState",
  "useEffect",
  "useContext",
  "useReducer",
  "redux",
  "store",
  "dispatch",
  "action",
  "reducer",
  "selector",
  "thunk",
  "saga",
  "webpack",
  "babel",
  "vite",
  "npm",
  "yarn",
  "pnpm",
  "package.json",
  "node_modules",
  "tsconfig.json",
  "eslint",
  "prettier",
  "jest",
  "mocha",
  "chai",
  "cypress",
  "playwright",
  "vitest",
  "docker",
  "kubernetes",
  "CI/CD",
  "git",
  "branch",
  "commit",
  "merge",
  "pull",
  "push",
  "rebase",
  "stash",
  "tag",
  "clone",
  "repository",
  "origin",
  "remote",
  "issue",
  "PR",
  "pipeline",
  "deployment",
  "production",
  "staging",
  "development",
  "testing",
  "lint",
  "build",
  "serve",
  "start",
  "dev",
  "test",
];

const MAX_LINES = 25; // скільки рядків реально поміщається в хедері

function createRandomCommand(): string {
  const len = Math.floor(Math.random() * 15) + 2; // 2–5 слів

  const parts: string[] = [];
  for (let i = 0; i < len; i++) {
    const idx = Math.floor(Math.random() * words.length);
    parts.push(words[idx]);
  }

  return parts.join(" ");
}

export default function Terminal() {
  const [lines, setLines] = useState<string[]>([]);

  useEffect(() => {
    let cancelled = false;

    async function loop() {
      while (!cancelled) {
        const cmd = createRandomCommand();

        setLines((prev) => {
          const next = [...prev, cmd];
          // залишаємо лише останні MAX_LINES
          if (next.length > MAX_LINES) {
            return next.slice(-MAX_LINES);
          }
          return next;
        });

        const delay = 500 + Math.random() * 500; // 400–800 ms
        await new Promise((r) => setTimeout(r, delay));
      }
    }

    // #0f0

    loop();

    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <Box
      sx={{
        maxHeight: "100vh",
        overflow: "hidden",
        width: "75vw",
        paddingLeft: "0",
        marginLeft: "0",
        position: "relative",
      }}
    >
      <Box
        sx={{
          userSelect: "none",
          "& *": {
            userSelect: "none",
            fontFamily: "monospace",
            fontSize: 12,
            color: "#FFF",
            overflow: "hidden",
            height: "100%",
            width: "100%",
            display: "flex",
            flexDirection: "column",
            filter: "blur(2px)",
          },
        }}
      >
        {lines.map((line, i) => (
          <div key={i}>
            <span style={{ color: "#FFF" }}>$ </span>
            {line}
          </div>
        ))}
      </Box>
    </Box>
  );
}
